# Generated by Django 6.0.5 on 2026-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
